steps:

- id: 'Deploy application to cluster'
  name: 'gcr.io/k8s-skaffold/skaffold:v1.36.0'
  entrypoint: 'bash'
  args:
  - '-c'
  - >
    gcloud container clusters get-credentials $_CLUSTER --region $_REGION --project $_PROJECT_ID;
    kubectl config set-context --current --namespace=$BRANCH_NAME;
    skaffold run -p gcb --default-repo=gcr.io/$_PROJECT_ID;


- id: 'create ingress'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['./bash.sh']
    
# Add more power, and more time, for heavy Skaffold build
options:
  machineType: 'E2_HIGHCPU_32'

# Add more power, and more time, for heavy Skaffold build
timeout: '6000s'


